name: Deploy Project 
on: push
jobs:
    lint: 
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Perform lint
              run: eslint --ext .jsx --fix src